export const ADDUSER = 'ADDUSER';
export const DELETEUSER = 'DELETEUSER'
export const EDITUSER = 'EDITUSER'
export const SETCURRENTUSER = 'SETCURRENTUSER'

export const ADDESTIMATEAPPOINTMENT = 'ADDESTIMATEAPPOINTMENT'
export const CONFIRMESTIMATEAPPOINTMENT = 'CONFIRMESTIMATEAPPOINTMENT'
export const REGISTERESTIMATEAPPOINTMENT = 'REGISTERESTIMATEAPPOINTMENT'
export const DENYESTIMATEAPPOINTMENT = 'DENYESTIMATEAPPOINTMENT'
export const EDITESTIMATEAPPOINTMENT = 'EDITESTIMATEAPPOINTMENT'

export const ADDWORKINGAPPOINTMENT = 'ADDWORKINGAPPOINTMENT'
export const CONFIRMWORKINGAPPOINTMENT = 'CONFIRMWORKINGAPPOINTMENT'
export const DENYWORKINGAPPOINTMENT = 'DENYWORKINGAPPOINTMENT'
export const EDITWORKINGAPPOINTMENT = 'EDITWORKINGAPPOINTMENT'

export const ADDREVIEW = 'ADDREVIEW'
export const DELETEREVIEW = 'DELETEREVIEW'
export const EDITREVIEW = 'EDITREVIEW'
